#!/bin/bash

# Script para configurar variables en Railway usando CLI

echo "🔧 Configurando variables de entorno en Railway..."

railway variables --set "MYSQL_ADDON_HOST=bj7lnbakskgcgngpmtma-mysql.services.clever-cloud.com"
railway variables --set "MYSQL_ADDON_DB=bj7lnbakskgcgngpmtma"
railway variables --set "MYSQL_ADDON_USER=u7imxhdxstbw6uuy"
railway variables --set "MYSQL_ADDON_PORT=3306"
railway variables --set "MYSQL_ADDON_PASSWORD=uaBOXOPi5TD9PEpIy8Uc"
railway variables --set "PORT=8000"
railway variables --set "API_GATEWAY_PORT=3000"
railway variables --set "NLP_SERVICE_PORT=8001"
railway variables --set "NOTIFICATION_SERVICE_PORT=3005"
railway variables --set "ANALYTICS_SERVICE_PORT=3006"
railway variables --set "NODE_ENV=production"
railway variables --set "APP_ENV=production"
railway variables --set "APP_DEBUG=false"
railway variables --set "CORS_ORIGIN=*"
railway variables --set "JWT_SECRET=upt-chat-system-jwt-secret-2024-super-secure-key"
railway variables --set "DIALOGFLOW_PROJECT_ID=upt-chat-fhps"
railway variables --set "DIALOGFLOW_LANGUAGE_CODE=es-ES"
railway variables --set "DIALOGFLOW_CREDENTIALS_PATH=./credentials/dialogflow-credentials.json"
railway variables --set "MODEL_CONFIDENCE_THRESHOLD=0.7"
railway variables --set "MAX_TOKENS=512"
railway variables --set "ENVIRONMENT=production"
railway variables --set "DEBUG=False"
railway variables --set "NLP_SERVICE_URL=http://localhost:8001"
railway variables --set "NOTIFICATION_SERVICE_URL=http://localhost:3005"
railway variables --set "ANALYTICS_SERVICE_URL=http://localhost:3006"

echo ""
echo "✅ Variables configuradas en Railway"
echo ""
echo "⚠️  IMPORTANTE: Debes configurar manualmente:"
echo "  MONGODB_URI = \${{MONGO_URL}}"
echo ""
echo "Para hacerlo:"
echo "1. Ve a Railway Dashboard"
echo "2. Agrega MongoDB addon"
echo "3. En Variables, agrega: MONGODB_URI=\${{MONGO_URL}}"
